  version: '3'
  services:
    userService:
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres_user
        POSTGRES_PASSWORD: password_user
        POSTGRES_DB: warBankDB
      ports:
        - 5432:5432
      volumes:
        - war-bank-db-data:/var/lib/postgresql/data
    app:
      build: .
      ports:
        - 3000:3000
      environment:
        DB_HOST: userService
        DB_USERNAME: postgres_user
        DB_PASSWORD: password_user
        DB_NAME: warBankDB
  volumes:
    war-bank-db-data:
